name:                entity
version:             0.1.0.0
github:              "SimonCockx/entity"
license:             BSD3
author:              "Simon Cockx"
maintainer:          "simon@sikanda.be"
copyright:           "2020 Simon Cockx"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SimonCockx/entity#readme>

dependencies:
- base >= 4.7 && < 5
- language-python
- language-typescript
- process
- containers
- mtl
- split
- data-default
- hvect
- template-haskell

default-extensions:
- RecordWildCards
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- DefaultSignatures
- MultiParamTypeClasses
- TypeFamilies
- TypeOperators
- ExistentialQuantification
- GADTs
- DataKinds
- UndecidableInstances
- PolyKinds
- KindSignatures
- ConstraintKinds
- RankNTypes
- ScopedTypeVariables

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  entity-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - entity

tests:
  entity-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - entity
